name: API Automation CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'   # built-in Maven cache

      - name: Show Java & Maven versions
        run: |
          java -version
          mvn -v

      # ✅ Do not fail the job if tests fail; Allure will still be generated
      - name: Run Tests
        run: mvn -B clean test || true
        # (Alternatively: continue-on-error: true)

      # ✅ Always build the Allure HTML report
      - name: Generate Allure Report
        if: always()
        run: mvn -B allure:report

      # ✅ Always upload raw Allure results (JSON)
      - name: Upload Allure Results (JSON)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          name: API Automation CI

          on:
            push:
              branches: [ "main" ]
            pull_request:
              branches: [ "main" ]
            workflow_dispatch:
          
          jobs:
            test:
              runs-on: ubuntu-latest
          
              steps:
                - name: Checkout repository
                  uses: actions/checkout@v4
          
                - name: Setup JDK 17
                  uses: actions/setup-java@v4
                  with:
                    distribution: 'temurin'
                    java-version: '17'
                    cache: 'maven'   # built-in Maven cache
          
                - name: Show Java & Maven versions
                  run: |
                    java -version
                    mvn -v
          
                # ✅ Do not fail the job if tests fail; Allure will still be generated
                - name: Run Tests
                  run: mvn -B clean test || true
                  # (Alternatively: continue-on-error: true)
          
                # ✅ Always build the Allure HTML report
                - name: Generate Allure Report
                  if: always()
                  run: mvn -B allure:report
          
                # ✅ Always upload raw Allure results (JSON)
                - name: Upload Allure Results (JSON)
                  if: always()
                  uses: actions/upload-artifact@v4
                  with:
                    name: allure-results
                    path: target/allure-results
                    if-no-files-found: warn
                    retention-days: 14
          
                # ✅ Always upload the ready-to-view HTML report
                - name: Upload Allure Report (HTML)
                  if: always()
                  uses: actions/upload-artifact@v4
                  with:
                    name: allure-report
                    path: target/site/allure-maven-plugin
                    if-no-files-found: warn
                    retention-days: 14
          
            # OPTIONAL: publish to GitHub Pages even if tests failed
            deploy:
              if: always()              # ← run regardless of test result
              runs-on: ubuntu-latest
              needs: test
          
              steps:
                - name: Download Allure Report Artifact
                  uses: actions/download-artifact@v4
                  with:
                    name: allure-report
                    path: site
          
                - name: Deploy to GitHub Pages
                  uses: peaceiris/actions-gh-pages@v4
                  with:
                    github_token: ${{ secrets.GITHUB_TOKEN }}
                    publish_dir: ./site
           path: target/allure-results
          if-no-files-found: warn
          retention-days: 14

      # ✅ Always upload the ready-to-view HTML report
      - name: Upload Allure Report (HTML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/site/allure-maven-plugin
          if-no-files-found: warn
          retention-days: 14

  # OPTIONAL: publish to GitHub Pages even if tests failed
  deploy:
    if: always()              # ← run regardless of test result
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Download Allure Report Artifact
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
